name: Mod Build

on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "src/**"
      - "gradle/**"
      - ".github/workflows/*"
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Configuration git
        run: |
          git config core.filemode false

      - name: Preprocess resources
        run: gradle preprocessResources

      - name: Build with Gradle
        run: gradle build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-Artifacts
          path: |
            LICENSE
            fabricWrapper/build/libs/*.jar
            fabricWrapper/build/tmp/submods/META-INF/jars/*.jar
